#!/bin/sh -ex

DEB_HOST_GNU_TYPE=$(dpkg-architecture -q DEB_HOST_GNU_TYPE)
PKG_CONFIG=$DEB_HOST_GNU_TYPE-pkg-config

# Work around us carrying upstream bf929fc3 as a Debian patch, which
# touches configure.ac (otherwise make tries to remake the build system):
touch aclocal.m4 configure config.status libknet/tests/Makefile.in libknet/tests/Makefile

# api-test-coverage would need a build, so call check-TESTS, not check:
make LIBS="$(${PKG_CONFIG} --libs libknet) \$(PTHREAD_LIBS) \$(dl_LIBS)" \
  VERBOSE=1 -C libknet/tests all check-TESTS || ret=$?

if [ "$AUTOPKGTEST_ARTIFACTS" ]; then
    mkdir "$AUTOPKGTEST_ARTIFACTS/libknet"
    mv libknet/tests/*.log libknet/tests/*.trs "$AUTOPKGTEST_ARTIFACTS/libknet"
fi

exit $ret
