#!/bin/sh -ex

./configure --disable-man

# api-test-coverage would need a build, so call check-TESTS, not check:
make LIBS="$(pkg-config --libs libknet) \$(PTHREAD_LIBS) \$(dl_LIBS)" \
  VERBOSE=1 -C libknet/tests all check-TESTS

mkdir -p /dev/net
[ -c /dev/net/tun ] || mknod -m666 /dev/net/tun c 10 200
make LIBS="$(pkg-config --libs libnozzle) \$(PTHREAD_LIBS) \$(libnl_LIBS)" \
  VERBOSE=1 -C libnozzle/tests all check-TESTS
